## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(['EIN', 'NAME'], axis=1, inplace=True)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_type_count = application_df['APPLICATION_TYPE'].value_counts()
application_type_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_type_count[application_type_count <= 200].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
CLASSIFICATION_count = application_df['CLASSIFICATION'].value_counts()
CLASSIFICATION_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
# application_df['CLASSIFICATION'].value_counts()
classification_counts = application_df['CLASSIFICATION'].value_counts()
filtered_counts = classification_counts[classification_counts > 1]
filtered_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts<1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
Convert_cat_dummies = pd.get_dummies(application_df)
Convert_cat_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
y = Convert_cat_dummies.IS_SUCCESSFUL.values
X = Convert_cat_dummies.drop(columns="IS_SUCCESSFUL").values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  80
hidden_nodes_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [14]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 7s 4ms/step - loss: 0.5691 - accuracy: 0.7233
Epoch 2/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5550 - accuracy: 0.7292
Epoch 3/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5533 - accuracy: 0.7302
Epoch 4/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5511 - accuracy: 0.7308
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5494 - accuracy: 0.7305
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7306
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5477 - accuracy: 0.7321
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7320
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7316
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5464 - accuracy: 0.7326
Epoch 11/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5453 - accuracy: 0.7341
Epoch 12/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5450 - accuracy: 0.7331
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7345
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7330
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5435 - accuracy: 0.7341
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7344
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7352
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7345
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5426 - accuracy: 0.7345
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5426 - accuracy: 0.7353
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5428 - accuracy: 0.7358
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7348
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7354
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7356
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7367
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7361
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7365
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7362
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5408 - accuracy: 0.7365
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7360
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7373
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7356
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7369
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7353
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7370
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7372
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5399 - accuracy: 0.7378
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5392 - accuracy: 0.7368
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7372
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7374
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7379
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7378
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7379
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7379
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7371
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5381 - accuracy: 0.7397
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5383 - accuracy: 0.7383
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7383
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7375
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7395
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7388
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7382
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7380
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5377 - accuracy: 0.7374
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7386
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7392
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7379
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7388
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7386
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7390
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7395
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7396
Epoch 63/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5366 - accuracy: 0.7393
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5366 - accuracy: 0.7387
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7395
Epoch 66/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5363 - accuracy: 0.7386
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5362 - accuracy: 0.7392
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7404
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7393
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7393
Epoch 71/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7398
Epoch 72/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7400
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7396
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7394
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7394
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7394
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7402
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7397
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7403
Epoch 80/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7402
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7395
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7389
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7398
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7393
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7396
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7399
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7403
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7404
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5350 - accuracy: 0.7399
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7403
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5352 - accuracy: 0.7403
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5345 - accuracy: 0.7415
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7406
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5345 - accuracy: 0.7402
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7399
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7404
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5344 - accuracy: 0.7400
Epoch 98/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5346 - accuracy: 0.7411
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7401
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5340 - accuracy: 0.7402

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5616 - accuracy: 0.7312 - 501ms/epoch - 2ms/step
Loss: 0.5615853071212769, Accuracy: 0.731195330619812

In [16]:
# Export our model to HDF5 file
import tensorflow as tf
nn.save('model.h5')

In [17]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).